apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-config
  namespace: reservation
data:
  REST_PORT: "8081"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:9092"
  KAFKA_TOPIC_CONFIRMED_RESERVATION: "reservation-confirmed"
  INVENTORY_GRPC_ADDRESS: "inventory-grpc.inventory.svc.cluster.local:50051"
  OTEL_ENDPOINT: "tempo.monitoring.svc.cluster.local:4317"
