apiVersion: v1
kind: Secret
metadata:
  name: reservation-secret
  namespace: reservation
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:secret@postgres.infra.svc.cluster.local:5432/reservation?sslmode=disable&TimeZone=Asia/Bangkok"
  POSTGRES_PASSWORD: "secret"
